export default {
  introduction: 'Introduction',
  'file-system': 'File System',
  'multi-file': 'Multi-File Read',
  shell: 'Shell',
  'todo-write': 'Todo Write',
  'task-management-zh': '任务管理工具对比',
  task: 'Task',
  'exit-plan-mode': 'Exit Plan Mode',
  'web-fetch': 'Web Fetch',
  'web-search': 'Web Search',
  memory: 'Memory',
  'mcp-server': 'MCP Servers',
  sandbox: 'Sandboxing',
};
